---
- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: Check - docker running
      shell: systemctl status docker | grep Active

    - name: Check - docker version
      shell: docker version|grep Version

- name: Check repos
  hosts: all
  tasks:
    - name: Check - repos
      yum:
        list: repolist
      register: result


- name: Verify NFS Shared Volumes on Hosts
  hosts: nfs
  tasks:
    - name: nfs is available
      shell: ansible nfs -m shell -a"exportfs"

- name: Install packages and config auth
  hosts: localhost
  tasks:
    - name: required packages are present
      yum:
        name:
          - openshift-ansible
          - atomic-openshift-clients
        state: present

#- name: Generate Inventory Hosts File
#  hosts: localhost
#  tasks:
#    - name: Generate Inventory script
#      script: ../scripts/generate_inventory.sh
